### PR TITLE
bugfix

### PR DESCRIPTION
**Pull request by youkaichao**
looks like a bug

### CODE REVIEW

**Comment by andylamp** [comment]
although functionally it's the same (due to how it works); I agree that for consistency it needs to be done.

**Comment by youkaichao** [comment]
It is a bug.
Consider `with -> to, left = true`, this will wrongly transfer the last element of `to` to be the head of `with`.

**Comment by youkaichao** [comment]
Actually, I encountered the bug and spend hours debugging, only to find those wrong lines. 
Anyway, the project is wonderful, thanks~

**Comment by andylamp** [comment]
ah cool - thanks for looking! please let me know if you find anything else :).

**Pull request merged**
